name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Set up Java
      uses: actions/setup-java@v1.0.0
      
      with:
        version: 1.13
      
    - name: Gradle Command
      run: ./gradlew build

    - name: Upload artifact (Slim JAR)
      uses: actions/upload-artifact@v1.0.0
      
      with:
        name: Slim JAR
        path: build/libs/*-SNAPSHOT.jar
        
    - name: Upload artifact (Production JAR)
      uses: actions/upload-artifact@v1.0.0
      
      with:
        name: Production JAR
        path: build/libs/*-SNAPSHOT-all.jar
        
    - name: Upload artifact (Sources JAR)
      uses: actions/upload-artifact@v1.0.0
      
      with:
        name: Sources JAR
        path: build/libs/*-SNAPSHOT-sources.jar
