name: Master

on:
  push:
    branches:    
      - master 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Set up Java
      uses: actions/setup-java@v1
      
      with:
        java-version: 1.16

    - name: Gradle Build
      run: sh gradlew build

    - name: Rename Artifacts
      run: |
        ls build/libs
        cp build/libs/*-all.jar build/

        mv build/libs/*-SNAPSHOT.jar build/libs/Mappy-slim.jar
        mv build/libs/*-SNAPSHOT-all.jar build/libs/Mappy.jar

    - name: Upload artifact (Slim JAR)
      uses: actions/upload-artifact@v1

      with:
        name: Slim JAR
        path: build/libs/Mappy-slim.jar

    - name: Upload artifact (Production JAR)
      uses: actions/upload-artifact@v1

      with:
        name: Production JAR
        path: build/libs/Mappy.jar

    - name: Copy production artifact back
      run: |
        cp build/*-all.jar build/libs/

    - name: Build Container
      run: "docker build --file Dockerfile -t teamjm/mappy:latest  -t teamjm/mappy:master -t teamjm/mappy:master-$(date +%s) ."

    - name: Publish Container
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
        docker push teamjm/mappy
